[package]
name = "conseil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.17.2"
iced = "0.9.0"
iced_aw = "0.5.2"
iced_native = "0.10.3"
time = "0.3.22"
